name: "Feature Request"
description: Suggest a new feature or improvement
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: What is the feature?
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this needed?
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: What must be true for this to be done?
  - type: dropdown
    attributes:
      label: Difficulty
      options: ["XS", "S", "M", "L", "XL"]
  - type: input
    attributes:
      label: Estimated hours
      placeholder: "e.g. 6h"