name: "Feature Request"
description: Suggest a new feature or improvement
title: "[request] "
labels: ["feature_request"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: What is the feature?
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this needed?
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: What must be true for this to be done?
  - type: dropdown
    id: effort
    attributes:
      label: Effort (est. time)
      description: Choose approximate difficulty / time requirement
      options:
        - XS 1h
        - S 3h
        - M 6h
        - L 10h
        - XL 15h
