name: "Idea"
description: Capture new ideas or opportunities
title: "[idea] "
labels: ["idea"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Briefly describe the idea or opportunity
  - type: textarea
    attributes:
      label: Potential impact / Motivation
  - type: textarea
    attributes:
      label: Possible next steps